on: [push]
name: Azure ARM v2
jobs:
  build-and-deploy:
    env:
      apiManagementServiceName: 'rutzsco-demo-apiops'
      apiManagmentPublisherEmail: 'scrutz@microsoft.com'
      apiManagmentPublisherName: 'rutzsco'
      apiManagmentLoggingEventHubNamespaceName: 'rutzsco-demo-apiops'
      apiManagmentLoggingEventHubName: 'telemetry'
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: CLI
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          ls

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infrastructure/main.bicep
        parameters: 
           apiManagementServiceName=${{ env.apiManagementServiceName }} 
           apiManagmentPublisherEmail=${{ env.apiManagmentPublisherEmail }} 
           apiManagmentPublisherName=${{ env.apiManagmentPublisherName }}
           apiManagmentLoggingEventHubNamespaceName=${{ env.apiManagmentLoggingEventHubNamespaceName }}
           apiManagmentLoggingEventHubName=${{ env.apiManagmentLoggingEventHubName }}
        failOnStdErr: false
